Repository CBIIT/icdc-codebase, pull requests merged in 2020-07, with the labels that each got.

#351 1410 - Fixed app crashing issue.
  src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
Labels: bug

#352 Study page will now show only case and below files in "File Type" section.
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: enhancement

#357 Changed the label applied to the arms and cohorts grid displayed within the Study Detail view.
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: Minor Fix

#356 fixed sunburst title text color in night mode.
  src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
Labels: Minor Fix

#358 Fixed: Title should not be shown in sunburst if mouse hovered element is not in filtered data.
  src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
Labels: enhancement

#359 Fix filter issues
  src/main/frontend/src/pages/dashboard/components/fileTable/fileView.js
  src/main/frontend/src/pages/dashboard/dashboardState.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: Minor Fix

#365 Download manifest from Cart
  src/main/frontend/src/pages/cart/cartView.js
Labels: enhancement

#366 Added Download CSV & Show/Hide Columns to every table in project.
  src/main/frontend/src/components/FileGrid/FileGridView.js
  src/main/frontend/src/pages/cart/cartView.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/pages/programDetail/components/programDetailView.js
  src/main/frontend/src/pages/studies/studiesView.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: enhancement

#371 Added Download CSV and Show/Hide column to CaseDetails View and Study Details View.
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
Labels: enhancement

#372 Minor Fix: Changed Label File Type.
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: Minor Fix

#376 removed "What" from Manifest.
  src/main/frontend/src/pages/cart/cartView.js
Labels: Minor Fix

#379 Implemented support for specific associations between Programs and the appropriate images.
  src/main/frontend/src/components/programImageConfig.js
  src/main/frontend/src/pages/programDetail/components/programDetailView.js
  src/main/frontend/src/pages/programs/components/programcard.js
Labels: enhancement

#381 Display additional case annotations within Case Listing and within Case Detail
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/caseConfig.js
  src/main/frontend/src/pages/dashboard/store/dashboardAction.js
  src/main/frontend/src/utils/graphqlQueries.js
Labels: Major Change, enhancement

#382 fix sidebar width issue & change table's title
  src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
  src/main/frontend/src/themes/dark.js
  src/main/frontend/src/themes/light.js
Labels: Minor Fix

#386 Tab style
  src/main/frontend/src/pages/caseDetail/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/caseConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabLabel.js
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/themes/light.js
Labels: enhancement

#387 Updated Cop Images & more
  src/main/frontend/src/assets/programCards/cop/copPrimary.png
  src/main/frontend/src/assets/programCards/cop/copSecondary.jpg
  src/main/frontend/src/components/NavBar/NavBarView.js
  src/main/frontend/src/components/programImageConfig.js
  src/main/frontend/src/pages/programs/components/programcard.js
Labels: enhancement
