Repository CBIIT/icdc-codebase, pull requests merged in 2020-08, with the labels that each got.

#388 Removed animation from Tab indicator.
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
Labels: Minor Fix

#389 fix Counts reported by the statistics bar do not fully align with counts reported via dashboard tabs
  src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: enhancement

#392 DEV ➡️ QA
  src/main/frontend/package-lock.json
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/caseConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: QA_Update

#393 Changed "Case" to "Cases" on the first tab.
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: Minor Fix

#395 Updating QA with Latest from DEV
  src/main/frontend/.env
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/caseDetail/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: QA_Update

#396 fix sample and file filtering issue
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: 🐛 Bugfix

#397 Google Analytics can capture react routes now.🥳🥳
  src/main/frontend/public/index.html
  src/main/frontend/src/components/GoogleAnalytics/GoogleAnalytics.js
  src/main/frontend/src/components/GoogleAnalytics/config.js
  src/main/frontend/src/components/Layout/LayoutView.js
Labels: enhancement

#398 udpate the button style
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
Labels: enhancement ⬆️

#399 Develop ➡️ QA
  src/main/frontend/public/index.html
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/components/GoogleAnalytics/GoogleAnalytics.js
  src/main/frontend/src/components/GoogleAnalytics/config.js
  src/main/frontend/src/components/Layout/LayoutView.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
Labels: QA_Update

#401 add ids to tables
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
Labels: enhancement ⬆️

#402 Develop
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
Labels: QA_Update

#403 update the button text
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: 🔧 Minor Fix

#405 UI Fixes
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabLabel.js
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
Labels: 🔧 Minor Fix

#406 Develop ➡️ QA (for 17th Aug, 2020)
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabLabel.js
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: QA_Update

#407 Fix message's showing time
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: 🔧 Minor Fix

#408 Develop ➡️ QA ( AUG 14 )
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: QA_Update

#409 update button text
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: 🔧 Minor Fix

#410 Develop ➡️ QA (Aug 17th)
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: QA_Update

#415 Hot fix from mQA_PMVP_1.2.0 ➡️ Master
  src/main/frontend/src/assets/cart/ExternalLink.svg
  src/main/frontend/src/pages/cart/customFooter.js
Labels: Pre-Release

#416 Hotfix
  src/main/frontend/.env
  src/main/frontend/src/pages/cart/cartView.js
  src/main/frontend/src/pages/cart/customFooter.js
  src/main/frontend/src/pages/landing/landingController.js
Labels: 🐛 Bugfix

#417 fix incorrect tootip
  src/main/frontend/src/components/NavBar/NavBarView.js
Labels: 🐛 Bugfix

#418 CleanWarning
  src/main/frontend/src/components/NavBar/NavBarView.js
  src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
  src/main/frontend/src/components/SideBar/SideBarView.js
  src/main/frontend/src/components/Stats/StatsView.js
  src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
  src/main/frontend/src/components/Widgets/WidgetView.js
  src/main/frontend/src/pages/about/aboutController.js
  src/main/frontend/src/pages/dashboard/components/tabFooter.js
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/pages/dashboard/dashboard.js
  src/main/frontend/src/pages/dashboard/dashboardController.js
  src/main/frontend/src/pages/programs/programs.js
Labels: enhancement ⬆️

#419 Relocate the horizontal scroll bar
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
Labels: enhancement ⬆️

#420 Minor Fix: Removed extra line from tabConfig.
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
Labels: 🔧 Minor Fix

#421 update button's padding
  src/main/frontend/src/pages/cart/cartView.js
Labels: enhancement ⬆️

#422 Replace image on About: Purpose page
  src/main/frontend/src/assets/about/Photo-About_Purpose.jpg
Labels: enhancement ⬆️

#423 Minor UI Improvements - Programs Spacing
  src/main/frontend/src/pages/programDetail/components/programDetailView.js
  src/main/frontend/src/pages/programs/components/programcard.js
  src/main/frontend/src/themes/dark.js
  src/main/frontend/src/themes/light.js
Labels: enhancement ⬆️
