Repository CBIIT/icdc-codebase, pull requests merged in 2020-09, with the labels that each got.

#424 update static page, extend the download function
  src/main/frontend/src/assets/about/ICDC_Data_Submission_Request_Template.docx
  src/main/frontend/src/pages/about/aboutBodyView.js
Labels: enhancement ⬆️

#425 Rebasing "QA" onto "Master"
  .github/workflows/check_spelling.yml
  .github/workflows/spellcheck.yaml
  src/main/frontend/.env
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/public/index.html
  src/main/frontend/src/assets/cart/ExternalLink.svg
  src/main/frontend/src/assets/programCards/cop/copPrimary.png
  src/main/frontend/src/assets/programCards/cop/copSecondary.jpg
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/components/GoogleAnalytics/GoogleAnalytics.js
  src/main/frontend/src/components/GoogleAnalytics/config.js
  src/main/frontend/src/components/Layout/LayoutView.js
  src/main/frontend/src/components/NavBar/NavBarView.js
  src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
  src/main/frontend/src/components/programImageConfig.js
  src/main/frontend/src/content/dev/aboutPagesContent.yaml
  src/main/frontend/src/content/prod/aboutPagesContent.yaml
  src/main/frontend/src/content/qa/aboutPagesContent.yaml
  src/main/frontend/src/content/stg/aboutPagesContent.yaml
  src/main/frontend/src/pages/cart/customFooter.js
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/caseDetail/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/caseConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
  src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/dashboard/components/tabLabel.js
  src/main/frontend/src/pages/dashboard/components/tabThemeConfig.js
  src/main/frontend/src/pages/dashboard/components/tabView.js
  src/main/frontend/src/pages/dashboard/store/dashboardAction.js
  src/main/frontend/src/pages/programDetail/components/programDetailView.js
  src/main/frontend/src/pages/programs/components/programcard.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
  src/main/frontend/src/themes/dark.js
  src/main/frontend/src/themes/light.js
  src/main/frontend/src/utils/dashboardUtilFunctions.js
  src/main/frontend/src/utils/graphqlQueries.js
Labels: Rebase

#427 Showing total number of case count on page load.
  src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
Labels: enhancement ⬆️

#428 Add subpages
  src/main/frontend/src/components/Layout/LayoutView.js
  src/main/frontend/src/components/NavBar/components/DropdownMenu.js
  src/main/frontend/src/pages/about/aboutController.js
Labels: enhancement ⬆️

#429 Update the text from my cart to my files
  src/main/frontend/src/pages/cart/cartView.js
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/dashboard/components/tabController.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: enhancement ⬆️

#430 Freeze bar
  src/main/frontend/src/pages/dashboard/dashboard.js
Labels: enhancement ⬆️

#432 Small fixes
  src/main/frontend/.env
  src/main/frontend/src/components/About/AbouBodyView.js
  src/main/frontend/src/components/FileGridWithCart/FileGridView.js
  src/main/frontend/src/components/Footer/FooterView.js
  src/main/frontend/src/components/Stats/StatsView.js
  src/main/frontend/src/pages/about/aboutBodyView.js
  src/main/frontend/src/pages/caseDetail/caseDetailView.js
  src/main/frontend/src/pages/modelPage/modelPageView.js
  src/main/frontend/src/pages/programDetail/components/programDetailView.js
  src/main/frontend/src/pages/programs/programs.js
  src/main/frontend/src/pages/studies/studiesView.js
  src/main/frontend/src/pages/studyDetail/components/studyDetailView.js
Labels: enhancement ⬆️

#433 Small fix
  src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
  src/main/frontend/src/content/dev/aboutPagesContent.yaml
  src/main/frontend/src/content/prod/aboutPagesContent.yaml
  src/main/frontend/src/pages/about/aboutBodyView.js
Labels: enhancement ⬆️

#434 Integrated ReactGA, Download Manifest & Remove file from cart Events can be tracked in google analytics.
  src/main/frontend/.env
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/Layout/LayoutView.js
  src/main/frontend/src/pages/cart/cartView.js
  src/main/frontend/src/utils/googleAnalytics/index.js
Labels: enhancement ⬆️

#435 Added Sitemap.xml to Public folder.
  src/main/frontend/public/sitemap.xml
Labels: enhancement ⬆️

#436 Added image alt text for about pages.
  src/main/frontend/src/pages/about/aboutBodyView.js
  src/main/frontend/src/pages/about/aboutController.js
Labels: 🔧 Minor Fix

#439 Changed alt text.
  src/main/frontend/src/pages/about/aboutController.js
Labels: 🔧 Minor Fix

#438 Fixed: "User Comments" text overlapping with text in textField.
  src/main/frontend/src/pages/cart/customFooter.js
Labels: 🔧 Minor Fix

#440 update the menu's acronyms
  src/main/frontend/src/components/NavBar/components/DropdownMenu.js
Labels: enhancement ⬆️

#441 Added Event Tracking for Tabs in Cases page.
  src/main/frontend/src/pages/dashboard/components/tabController.js
Labels: enhancement ⬆️

#442 Added GA Event Tracking for Facets
  src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
Labels: enhancement ⬆️

#443 enable the link featuer in the talbe of static page
  src/main/frontend/.env
  src/main/frontend/src/assets/about/About-Table-ExternalLink.svg
  src/main/frontend/src/content/prod/aboutPagesContent.yaml
  src/main/frontend/src/pages/about/aboutBodyView.js
Labels: enhancement ⬆️

#444 update the static page settings
  src/main/frontend/src/assets/about/Photo-About_BPSC.jpg
  src/main/frontend/src/assets/about/Photo-About_DGAB.jpg
  src/main/frontend/src/components/NavBar/components/DropdownMenu.js
  src/main/frontend/src/pages/about/aboutBodyView.js
  src/main/frontend/src/pages/about/aboutController.js
Labels: enhancement ⬆️

#445 Static page
  pom.xml
  src/main/frontend/src/assets/about/Photo-About_Developer.jpg
  src/main/frontend/src/assets/about/Photo-About_Purpose.jpg
Labels: enhancement ⬆️
